project_id = "hipomusjocacncjsvgfa"

[functions.create-storage-bucket]
verify_jwt = false

[functions.payfast-payment]
verify_jwt = true

[functions.send-order-status-email]
verify_jwt = false

[functions.send-outbid-notification]
verify_jwt = false
